apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-nodejs-app
  name: my-nodejs-app
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: my-nodejs-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - image: khuhshveer/01vites:$(tag)
        imagePullPolicy: IfNotPresent
        name: my-nodejs-app
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nodejs-app
  name: my-nodejs-app
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: my-nodejs-app
  sessionAffinity: None
  type: LoadBalancer